//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------
// System.Internal.HandleChangeEventHandler
#if NETCOREAPP3_1_OR_GREATER
namespace System.Internal;
internal delegate void HandleChangeEventHandler(string handleType, IntPtr handleValue, int currentHandleCount);
#endif