//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------
#if NETCOREAPP3_1_OR_GREATER
namespace System.Windows.Forms;
using System;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Windows.Forms.Natives;
internal static class ControlPrivate {
    public static IntPtr SetUpPalette(IntPtr dc, bool force, bool realizePalette) {
        IntPtr halftonePalette = Graphics.GetHalftonePalette();
        IntPtr intPtr = SafeNativeMethods.SelectPalette(new HandleRef(null, dc), new HandleRef(null, halftonePalette), (!force) ? 1 : 0);
        if (intPtr != IntPtr.Zero && realizePalette) {
            SafeNativeMethods.RealizePalette(new HandleRef(null, dc));
        }
        return intPtr;
    }
}
#endif