//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------
// System.Windows.Forms.SafeNativeMethods
#if NETCOREAPP3_1_OR_GREATER
namespace System.Windows.Forms.Natives;
using System.Runtime.InteropServices;
using System.Security;
[SuppressUnmanagedCodeSecurity]
internal static class SafeNativeMethods {
    [DllImport("gdi32.dll", CharSet = CharSet.Auto, EntryPoint = "DeleteObject", ExactSpelling = true, SetLastError = true)]
    internal static extern bool IntDeleteObject(HandleRef hObject);

    public static bool DeleteObject(HandleRef hObject) {
        System.Internal.HandleCollector.Remove((IntPtr)hObject, NativeMethods.CommonHandles.GDI);
        return IntDeleteObject(hObject);
    }

    [DllImport("user32.dll", CharSet = CharSet.Auto, ExactSpelling = true)]
    public static extern bool TrackPopupMenuEx(HandleRef hmenu, int fuFlags, int x, int y, HandleRef hwnd, NativeMethods.TPMPARAMS tpm);

    [DllImport("gdi32.dll", CharSet = CharSet.Auto, ExactSpelling = true, SetLastError = true)]
    public static extern IntPtr SelectPalette(HandleRef hdc, HandleRef hpal, int bForceBackground);

    [DllImport("gdi32.dll", CharSet = CharSet.Auto, ExactSpelling = true, SetLastError = true)]
    public static extern int RealizePalette(HandleRef hDC);

    [DllImport("user32.dll", CharSet = CharSet.Auto, ExactSpelling = true)]
    public static extern bool DrawMenuBar(HandleRef hWnd);
}
#endif